### ISSUE TITLE
Benchmark running error？

### ISSUE THREAD

**Issue by tensorflowt** [xdit-project/xDiT#154] opened 2024-07-30 02:08 UTC
![image](https://github.com/user-attachments/assets/954977d0-2f59-4db2-8185-7a84e69d6734)

What is the reason for this? Tks！

**Comment by Steaunk** [comment] 2024-07-30 02:24
Could you also attach your cmd & environment?

**Comment by tensorflowt** [comment] 2024-07-30 02:35
`Package                  Version
------------------------ ---------------
accelerate               0.33.0
attrs                    21.2.0
Automat                  20.2.0
Babel                    2.8.0
bcrypt                   3.2.0
beautifulsoup4           4.12.3
blinker                  1.4
certifi                  2020.6.20
chardet                  4.0.0
click                    8.0.3
cloud-init               18.5
colorama                 0.4.4
command-not-found        0.3
configobj                5.0.6
constantly               15.1.0
cryptography             3.4.8
dbus-python              1.2.18
diffusers                0.29.0
distro                   1.7.0
distro-info              1.1build1
DistVAE                  0.0.0b4
filelock                 3.15.4
fsspec                   2024.6.1
ftfy                     6.2.0
httplib2                 0.20.2
huggingface-hub          0.24.2
hyperlink                21.0.0
idna                     3.3
importlib-metadata       4.6.4
incremental              21.3.0
jeepney                  0.7.1
Jinja2                   3.0.3
jsonpatch                1.32
jsonpointer              2.0
jsonschema               3.2.0
keyring                  23.5.0
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
MarkupSafe               2.0.1
mlnx-tools               -5.2.0-
more-itertools           8.10.0
mpmath                   1.3.0
netifaces                0.11.0
networkx                 3.3
numpy                    1.26.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.19.3
nvidia-nvjitlink-cu12    12.5.82
nvidia-nvtx-cu12         12.1.105
oauthlib                 3.2.0
packaging                24.1
pexpect                  4.8.0
pillow                   10.4.0
pip                      22.0.2
psutil                   6.0.0
ptyprocess               0.7.0
pyasn1                   0.4.8
pyasn1-modules           0.2.1
PyGObject                3.42.1
PyHamcrest               2.0.2
PyJWT                    2.3.0
pyOpenSSL                21.0.0
pyparsing                2.4.7
pyrsistent               0.18.1
pyserial                 3.5
python-apt               2.3.0+ubuntu2.1
python-debian            0.1.43ubuntu1
pytz                     2022.1
PyYAML                   5.4.1
regex                    2024.7.24
requests                 2.25.1
safetensors              0.4.3
SecretStorage            3.3.1
sentencepiece            0.2.0
service-identity         18.1.0
setuptools               59.6.0
six                      1.16.0
sos                      4.3
soupsieve                2.5
ssh-import-id            5.11
sympy                    1.13.1
systemd-python           234
tokenizers               0.19.1
torch                    2.2.0
torchaudio               2.2.0
torchvision              0.17.0
tqdm                     4.66.4
transformers             4.43.3
triton                   2.2.0
Twisted                  22.1.0
typing_extensions        4.12.2
ubuntu-advantage-tools   27.9
ubuntu-drivers-common    0.0.0
ufw                      0.36.1
unattended-upgrades      0.1
urllib3                  1.26.5
wadllib                  1.3.6
wcwidth                  0.2.13
wheel                    0.37.1
xdit                     0.1
xkit                     0.0.0
zipp                     1.0.0
zope.interface           5.4.0`

cmd:
![image](https://github.com/user-attachments/assets/5b9ca747-eaaa-42b4-a618-f41e5b066f46)

benchmark.sh
![image](https://github.com/user-attachments/assets/98d4b293-1e89-4870-b221-1f8f27aa0ec5)

**Comment by Steaunk** [comment] 2024-07-30 02:54
You should `pip install yunchang`

**Comment by tensorflowt** [comment] 2024-07-30 03:03
![69006475c941e2ce945df327d4a81939](https://github.com/user-attachments/assets/652b8b12-2206-4a1a-87d6-c926b0375ce1)

Excuse me, is there any requirement for the yunchang version? Is there any requirement for the torch version?

cmd
`pip install yunchang`

**Comment by tensorflowt** [comment] 2024-07-30 03:20
![image](https://github.com/user-attachments/assets/eddbb6e0-ad83-4d5a-be22-84dd1537ccfb)
Then there is still this error！

**Comment by Steaunk** [comment] 2024-07-30 03:44
I think there are some mismatch between flash_attn & yunchang. Could you try install yunchang from source code? https://github.com/feifeibear/long-context-attention/tree/main

**Comment by tensorflowt** [comment] 2024-07-30 04:09
no working，same issues.

**Comment by Steaunk** [comment] 2024-07-30 04:18
@feifeibear

**Comment by Steaunk** [comment] 2024-07-30 05:51
@tensorflowt 
Here I provided some env of mine for your reference. I can run this code successfully.
```
torch 2.3.0a0+6ddf5cf85e.nv24.04
yunchang==0.2
flash-attn==2.4.2
diffusers==0.29.0
```

**Comment by feifeibear** [comment] 2024-07-30 08:32
@tensorflowt Hi, you should install yunchang by pip install .
https://github.com/feifeibear/long-context-attention

**Comment by feifeibear** [comment] 2024-07-30 12:06
@tensorflowt could you please provide the script to reproduce the bug.

**Comment by feifeibear** [comment] 2024-08-09 01:43
close this issue, because we can not reproduce the problem and the xDiT has upgraded.

**Closed by feifeibear** 2024-08-09 01:43 UTC
